### ISSUE TITLE
Token Cloning: TokenDocument5e#actorData Error

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/Beneos-Multilevel-Tokens#1]
The Token cloning is "sort of" broken for several months now. It throws errors if a token is cloned.

- The cloning function allows to clone a token from a source drawing to a destination drawing. That is used to show tokens that should be seen on your scene but AREN'T on your scene (For example if you are in the second floor map and "should" see someone on the first floor map. MLT uses the same drawings as it uses for the teleportation but just clones from source to destination.

Every time you move a token in the "source" drawing area a TokenDocument Error is thrown.

[localhost-1718376971541.log](https://github.com/user-attachments/files/15839758/localhost-1718376971541.log)

https://github.com/BeneosBattlemaps/Beneos-Multilevel-Tokens/assets/93905181/ab442c59-ba50-4eee-903e-5b828700a6db

**Comment by LeRatierBretonnien** [comment]
Sorry, I do not see the issue here. The token copy function is working. The warning in the console are not due to Multilevel Tokens at all, seems related to libWrapper. Hence the bug must be redirected to the libWrapper module.
