### ISSUE TITLE
Macros executing one movement later than intended.

### ISSUE THREAD

**Issue by raepng** [BeneosBattlemaps/Beneos-Multilevel-Tokens#12]
Hi, I installed Multilevel Tokens today and I have run into a small issue. I am using the macro function to execute a macro that changes the tokens elevation. However for some reason the macro is always executed one movement later than it should. I checked all three boxes for update on enter, update on leave and update on movement. When my token enters the area for the first time, nothing happens. When I then move the token while inside the area it updates. When I move the token out of the area and then move it again while it is not inside the area, the macro triggers on that second move as well while it should - to my understanding - only trigger once when exiting the area. I am on Foundry v12.
My macro is
```
console.log("test");
token.update({ "elevation": args[0] });
```
Please tell me if I am doing something insanely wrong.

**Comment by LeRatierBretonnien** [comment]
Fixed with #17
