### ISSUE TITLE
[Feature] Add option to set elevation on teleport

### ISSUE THREAD

**Issue by morepurplemorebetter** [BeneosBattlemaps/Beneos-Multilevel-Tokens#18]
I would like the token to gain the elevation set on the arrival teleportation drawing. I have now done this by altering the code of this module to always do this, see below.

If you are willing to consider this feature addition, it could also be added as a checkbox so it would be optional.

I changed the following line in multilevel.js:
```js
destinations.push([foundry.utils.duplicate(token), outScene, animate, position]);
```
to
```js
const duplToken = foundry.utils.duplicate(token);
if (outRegion.elevation !== undefined) duplToken.elevation = outRegion.elevation;
destinations.push([duplToken, outScene, animate, position]);
```

If you'd like, I would happily make a PR for this.

**Comment by LeRatierBretonnien** [comment]
Yes, thanks, it seems correct, feel free to push a PR for this
