### ISSUE TITLE
Slowness when MLT is active

### ISSUE THREAD

**Issue by lucaspicerni** [BeneosBattlemaps/Beneos-Multilevel-Tokens#20]
Hello! Even without any active modules, other than MLT, I'm experiencing a lot of lag. Foundry is very slow, even on small maps, with few lights/walls/tokens/etc, including on maps where there is no MLT functionality being used. I didn't find any errors in the console, but it's definitely MLT, since it happens with only it activated, but not with all my other 117 modules (except MLT). Usually after 2 or 3 minutes with the same map active, the lag reduces, it seems like a loading problem.

I'm using MLT 1.7.5, Foundry 12.311 and D&D 5e 4.0.4. My module settings are: all activated, except for chat bubble synchronization. I'm using Foundry in medium performance mode, with 60 FPS.

Sorry for not having more information, please let me know if there is any other test I can do! Thanks.

**Comment by LeRatierBretonnien** [comment]
It seems your are the only one with this issues, so it is difficult to state why do you see "slowdown". Could you provide more details about what you call "Slowdown" exactly ?

**Comment by lucaspicerni** [comment]
The screen freezes for 1-2 seconds, the interface stops responding. Sometimes I click on a button, close or open a window and the software takes a while to respond. Foundry's weather effects freeze and move constantly. The canvas takes a while to move or moves with small freezes.

I performed tests with several maps and without any other modules, but it was an already populated world. Later today I will make a new instance of Foundry installation, install MLT and test with an empty world, and then I will report back.

Thank you!

**Comment by lucaspicerni** [comment]
Hello again! I have run several tests and have not been able to find the source of the problem. It only occurs in a specific world. Even enabling only MLT and resetting the settings for that world to default, it still occurs. However, I have not been able to find a specific setting or situation in which it occurs. Therefore, I think this ticket can be closed. Sorry for the inconvenience!

**Comment by LeRatierBretonnien** [comment]
Close as unique case
