### ISSUE TITLE
[Feature Request] Allow elevation change on clone

### ISSUE THREAD

**Issue by manuel-hegner** [BeneosBattlemaps/Beneos-Multilevel-Tokens#21]
Heyo,

it would be an amazing addition to change the elevation of cloned tokens. This would be super useful in the usecase where a clone region represents a visible lower level that is represented on another map. Without the elevation change systems do not calculate the distance correctly. One way to do this would be to modify the elevation of the tokens based on the difference in the elevation of the drawing source and drawing.

**Comment by manuel-hegner** [comment]
I think all that would be needed would be a 
```
data.elevation=token.elevation-sourceRegion.elevation+targetRegion.elevation;
```

**Comment by LeRatierBretonnien** [comment]
Implemented in a4d9196

**Comment by manuel-hegner** [comment]
It hink a4d9196 only changed the teleporting behavior but the the cloning one. The same code is probably also needed in _getReplicatedTokenCreateData

**Comment by manuel-hegner** [comment]
And the condition kind of breaks the code, as it evaluates to false if any of the two regions is at elevation 0.

**Comment by LeRatierBretonnien** [comment]
Yes, good point. Changed pushed
