### ISSUE TITLE
[Feature] Region Support

### ISSUE THREAD

**Issue by ChasarooniZ** [BeneosBattlemaps/Beneos-Multilevel-Tokens#5]
It may be worth converting some of the Module's Features to region as so (in my thoughts):
- Cloning
  - Most important unique feature to copy, worth doing it for sure
- Teleport 
  -  Unnecessary to port, already included in core
- Levels
  - Would also be nice

**Comment by BeneosBattlemaps** [comment]
Hey Chas,
the Core Regions functionality does not yet replace MLT's teleport
features, as they currently only work in the world in which they were
created (ID based). However, content creators in particular are dependent
on their teleporters also working in users' worlds, and the MLT identifier
is the only cross-world identifier that works. At least this is the current
status of our tests. We are currently looking into whether Regions can
adopt these functionalities for all use cases.

Best,
Ben

**Comment by ChasarooniZ** [comment]
Ah I see, makes perfect sense thank you for the detailed explanation <3
