### ISSUE TITLE
click-to-activate teleport behaves like click and drag

### ISSUE THREAD

**Issue by ScoobyTchotchke** [BeneosBattlemaps/Beneos-Multilevel-Tokens#7]
When configuring click-to-activate teleports, upon clicking the note to activate the teleport, the token(s) teleport, but the mouse cursor registers the click of then note as click-and-drag, causing the orange selection box to appear, requiring players and the GM to click a second time, potentially selecting erroneous elements then having to deselect them, slowing down and annoying everyone.

Steps to replicate:

1. Draw two regions on the map.
2. Under the Multilevel tab for those regions make sure "In" and "Out" are activated and the "Teleport Identifier" is identical for both regions.
3. Make sure "Activate via map note" is checked.
4. Create the necessary map note(s) for both regions.
5. Click on the map note, and move your mouse.  You should see the orange click-and-drag select box follow your mouse even though you're not holding the LMB down.

**Comment by LeRatierBretonnien** [comment]
Thanks for your report, ticket is under investigation
