### ISSUE TITLE
Error during Module update.

### ISSUE THREAD

**Issue by Deadlander** [BeneosBattlemaps/Beneos-Multilevel-Tokens#8]
When running update of the module, this error appears:
![image](https://github.com/BeneosBattlemaps/Beneos-Multilevel-Tokens/assets/13036735/a2cecd0f-b186-4f60-8bd1-7949de14d902)

Not sure what causes it, but it happens every time.

**Comment by LeRatierBretonnien** [comment]
No issue here, I tested it again. Could you remove the module and install it again (instead of updating) ?

**Comment by Deadlander** [comment]
That fixed it!
