### ISSUE TITLE
Players Cannot Teleport

### ISSUE THREAD

**Issue by swiftflag** [BeneosBattlemaps/Beneos-Multilevel-Tokens#9]
I was wondering if there was a way to make it so tokens will teleport when their players move them, instead of just when the GM moves the tokens into the teleport zone. Is that possible?

**Comment by LeRatierBretonnien** [comment]
I need to check that, yes. Sounds feasible.

**Comment by LeRatierBretonnien** [comment]
Quick check : if this checkbox is false
![image](https://github.com/user-attachments/assets/cf940728-f644-4a3f-851d-b903c375aa7b)

then player can teleport their tokens while moving.

**Comment by swiftflag** [comment]
I saw that! I think that could work too, but I was talking about when players just move their tokens into a zone, like when the GM does it it automatically teleports them, but when players do it it does not work, is there a way to make that work?

**Comment by LeRatierBretonnien** [comment]
You probably have an issue or something else in your settings : player can be teleported on their own, with move from the GM. Either you are using a deprecated version of MLT, either you have a conflict/issue in your world.
